### ISSUE TITLE
Error when trying to install from npm

### ISSUE THREAD

**Issue by TChong** [mortend/android-build-tools#1]
I get this error when I try to install from npm.

**COMMAND LINE:**
&gt; android-build-tools@0.3.1 install /Users/User/.npm-packages/lib/node_modules/android-build-tools
&gt; bash install.sh

: command not found 
: command not found 
: command not found 
: command not found: 
'nstall.sh: line 12: syntax error near unexpected token \`{
'nstall.sh: line 12: \`function fatal-error {
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! android-build-tools@0.3.1 install: \`bash install.sh\`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the android-build-tools@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/User/.npm/_logs/2019-02-01T09_31_55_047Z-debug.log

**LOG FILE:**
[2019-02-01T09_31_55_047Z-debug.log](https://github.com/mortend/android-build-tools/files/2820987/2019-02-01T09_31_55_047Z-debug.log)

**Comment by mortend** [comment]
Thank you for reporting.

It turned out that line endings were somehow converted to CRLF in the tarball published on npm, and repackaging fixed the issue. If you reinstall now it should work.

**Comment by Pasvaz** [comment]
I think it happened again, I'm having the same exact issue with android-build-tools@1.5.1 on Mac

`
npm install android-build-tools -g

> android-build-tools@1.5.1 install /usr/local/lib/node_modules/android-build-tools
> xbash src/install.bash

: command not foundine 2: 
: command not foundine 6: 
: command not foundine 10: 
'rc/install.bash: line 11: syntax error near unexpected token `{
'rc/install.bash: line 11: `function fatal-error {
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! android-build-tools@1.5.1 install: `xbash src/install.bash`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the android-build-tools@1.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by mortend** [comment]
@Pasvaz Sorry about the incident. 

The problem was fixed in 1.5.2 and measures taken to prevent it from happening again.
