### ISSUE TITLE
Evironment Variables Setting

### ISSUE THREAD

**Issue by christopherwoo** [mortend/android-build-tools#2]
How to setup evironment variables, such as ANDROID_SDK, ANDROID_NDK...

**Comment by mortend** [comment]
The script installs to a known location so you can set your variables to point to that location, something like below.

**macOS**

```
export ANDROID_SDK=~/Library/Android/sdk
export ANDROID_NDK=~/Library/Android/sdk/ndk-bundle
```

**Windows**

```
set ANDROID_SDK=%LOCALAPPDATA%\Android\sdk
set ANDROID_NDK=%LOCALAPPDATA%\Android\sdk\ndk-bundle
```
