### ISSUE TITLE
i cant install android-build-tools

### ISSUE THREAD

**Issue by furang1933** [mortend/android-build-tools#3]
I have an error and question.

Q: First of all, my mac has android build tools in '~/Library/Android/sdk'
and set PATH(ANDROID_HOME, ANDROID_SDK, ANDROID_SDK_ROOT)
to same path.(there is android build tools)
Do i still have to install it?

E: When i installed your android-build-tools package from npm on my mac with sudo,
it occurs an error in spite of i installed xbash too.

This is the error message.

Eun-gwangui-MacBookPro:Seoul furang$ sudo npm install -g android-build-tools

> android-build-tools@1.0.0 install /usr/local/lib/node_modules/android-build-tools
> xbash install.bash

Downloading https://dl.google.com/android/repository/sdk-tools-darwin-4333796.zip
Warning: Failed to create the file sdk.zip: Permission denied

curl: (23) Failed writing body (0 != 1388)

ERROR: Download failed.

Please try again later, or open an issue on GitHub (https://github.com/mortend/android-build-tools/issues).
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! android-build-tools@1.0.0 install: `xbash install.bash`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the android-build-tools@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/furang/.npm/_logs/2019-07-29T11_33_55_060Z-debug.log

**Comment by furang1933** [comment]
Additional, if i build my unoproj file with uno, it occurs an error in spite of i set Android SDK, NDK.
here's my error message.




Eun-gwangui-MacBookPro:Seoul furang$ sudo uno build android --configuration=release SeoulChildrenCare.unoproj 
Uno 1.12.1 (build 352) macOS 10.14 x86_64 ae63e36
Copyright © 2018-present Fuse Open

Configuring  0.18 s                                                                                                   
Target is up-to-date -- stopping build (pass --force to override)
Building Android app
ERROR: Could not locate the Android SDK or NDK.

These dependencies can be acquired by installing 'android-build-tools':

    npm install android-build-tools -g

(unknown): E0200: Android build failed
0.04 s

Build completed in 0.22 seconds
    1 error

**Comment by mortend** [comment]
Thank you for reporting.

The scripts expects `/usr/local/lib/node_modules` to be writeable (without `sudo`), and it looks like the problem is that your `node_modules` directory is not writeable.

I think you can fix your problem by resetting permissions:
```
sudo chown -R "$(whoami)" "$(npm prefix -g)/lib/node_modules"
```

And then reinstalling (without `sudo`):
```
npm install android-build-tools -g
```

**Comment by furang1933** [comment]
wow thank you!
very nice, it works!
