### ISSUE TITLE
android-build-tools fail to download

### ISSUE THREAD

**Issue by PierreLouer** [mortend/android-build-tools#4]
I need help please to install this package.

sh-3.2# npm install android-build-tools -g

> android-build-tools@1.1.0 install /usr/local/lib/node_modules/android-build-tools
> xbash install.bash

Downloading https://dl.google.com/android/repository/sdk-tools-darwin-4333796.zip
Warning: Failed to create the file sdk.zip: Permission denied

curl: (23) Failed writing body (0 != 1178)

ERROR: Download failed.

Please try again later, or open an issue on GitHub (https://github.com/mortend/android-build-tools/issues).
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! android-build-tools@1.1.0 install: `xbash install.bash`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the android-build-tools@1.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2019-11-07T09_54_29_470Z-debug.log
sh-3.2# 

I'm running on Mac Mojave with root

**Comment by mortend** [comment]
Hmm, it sounds like you don't have permission to write `sdk.zip` inside `/usr/local/lib/node_modules/android-build-tools`.

[This article](https://flaviocopes.com/npm-fix-missing-write-access-error/) suggests to fix the problem by running the following command.
```
sudo chown -R $USER /usr/local/lib/node_modules
```

Another approach may be to change NPMs install directory to `~/.npm-global`, as described [in NPM documentation](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally).

Hope this helps!

**Comment by mortend** [comment]
Another user reported a similar problem a few months ago and we found a solution in https://github.com/mortend/android-build-tools/issues/3#issuecomment-515984966.

**Comment by mortend** [comment]
I just released a new version that will download `sdk.zip` to a location under your home directory, which hopefully fixes the `Permission denied` issue.

Please try to reinstall.

**Comment by PierreLouer** [comment]
> I just released a new version that will download `sdk.zip` to a location under your home directory, which hopefully fixes the `Permission denied` issue.
> 
> Please try to reinstall.

This work fine fore me thanks
