### ISSUE TITLE
Install does not works on mac

### ISSUE THREAD

**Issue by Paulofsr** [mortend/android-build-tools#7]
Hi! The installation did not work on mac (macOS Sierra), follow the installation log.
 

> sudo npm install android-build-tools -g --force
> 
> npm WARN using --force I sure hope you know what you are doing.
> 
>    android-build-tools@1.3.0 install /usr/local/lib/node_modules/android-build-tools
>    xbash install.bash
> 
> Accepting licenses
> install.bash: line 153: sdkmanager.log: Permission denied
> cat: sdkmanager.log: No such file or directory
> 
> ERROR: Install failed.
> 
> Please read output for clues, or open an issue on GitHub (https://github.com/mortend/android-build-tools/issues).
> 
> Please note that JDK8 (not 9+) is required to install Android SDK. Get OpenJDK8 from https://adoptopenjdk.net/ and try again.
> + android-build-tools@1.3.0
> updated 1 package in 5.217s

**Comment by Paulofsr** [comment]
I think that's the problem:

When 

`touch "$zip" || permission-error "$zip"` (Line 145 on install.bash)


When I debug the variable $zip is:
> -bash: /Users/paulofrancisco/Library/Android/sdk.zip: Permission denied

**Comment by mortend** [comment]
Thank you for reporting this issue. :)

I believe the first comment should be solved on branch `log-file`, fixing the following error.
```
install.bash: line 153: sdkmanager.log: Permission denied
cat: sdkmanager.log: No such file or directory
```

About the second comment, you can try the following command to reset permissions of your `/Users/paulofrancisco/Library/Android` directory.
```
sudo chown -R "$(whoami)" "/Users/paulofrancisco/Library/Android"
```

---

- Can you please test the latest build from branch `log-file` and report if it fixes the problem?
```
npm install -g -f https://ci.appveyor.com/api/buildjobs/ak94p9xayc2cjb54/artifacts/android-build-tools-1.3.0.tgz
```

**Comment by Paulofsr** [comment]
Not yet! I tried to run and a new error appeared. Follow..

> sudo npm install -g -f https://ci.appveyor.com/api/buildjobs/ak94p9xayc2cjb54/artifacts/android-build-tools-1.3.0.tgz
> Password:
> npm WARN using --force I sure hope you know what you are doing.
> 
>   android-build-tools@1.3.0 install /usr/local/lib/node_modules/android-build-tools
>   xbash install.bash
> 
> Accepting licenses
> Exception in thread "main" java.lang.RuntimeException: Cannot create directory /var/empty/.android
> 	at com.android.utils.FileUtils.mkdirs(FileUtils.java:215)
> 	at com.android.prefs.AndroidLocation.getFolder(AndroidLocation.java:144)
> 	at com.android.sdklib.repository.AndroidSdkHandler.lambda$getInstance$3(AndroidSdkHandler.java:229)
> 	  at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
> 	  at com.android.sdklib.repository.AndroidSdkHandler.getInstance(AndroidSdkHandler.java:224)
> 	  at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
> 	  at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
> 
> ERROR: Install failed.
> 
> Please read output for clues, or open an issue on GitHub (https://github.com/mortend/android-build-tools/issues).
> 
> Please note that JDK8 (not 9+) is required to install Android SDK. Get OpenJDK8 from https://adoptopenjdk.net/ and try again.
> + android-build-tools@1.3.0
> updated 1 package in 9.363s

**Comment by mortend** [comment]
Hmm, I see `/var/empty/.android` in your log. This should've resolved to `/Users/paulofrancisco/.android`, so maybe the `HOME` variable is not defined on your system.

Can you try this?
```
export HOME=/Users/paulofrancisco
npm install -g -f https://ci.appveyor.com/api/buildjobs/ak94p9xayc2cjb54/artifacts/android-build-tools-1.3.0.tgz

```

**Comment by mortend** [comment]
I have another build that attempts to set HOME if not set already.
```
sudo npm install -g -f https://ci.appveyor.com/api/buildjobs/xhdt0dtx2o4jb18o/artifacts/android-build-tools-1.3.0.tgz
```

If that doesn't work: Try running the command without using `sudo`. `sudo` is probably what is causing your `HOME` variable to become undefined inside the script. 
```
npm install -g -f https://ci.appveyor.com/api/buildjobs/xhdt0dtx2o4jb18o/artifacts/android-build-tools-1.3.0.tgz
```

**Comment by Paulofsr** [comment]
@mortend, sorry for my incompetence, but it still didn't work. 
See below the steps I've already taken:

I set the `HOME` variable:
> paulofrancisco$ export HOME=/Users/paulofrancisco/

Ok! Let's to intallation:

1. Buildjob `ak94p9xayc2cjb54`:

> paulofrancisco$ sudo npm install -g -f https://ci.appveyor.com/api/buildjobs/ak94p9xayc2cjb54/artifacts/android-build-tools-1.3.0.tgz
> npm WARN using --force I sure hope you know what you are doing.
> 
> '> android-build-tools@1.3.0 install /usr/local/lib/node_modules/android-build-tools
> '> xbash install.bash
> 
> Accepting licenses
> Exception in thread "main" java.lang.RuntimeException: Cannot create directory /var/empty/.android
> 	at com.android.utils.FileUtils.mkdirs(FileUtils.java:215)
> 	at com.android.prefs.AndroidLocation.getFolder(AndroidLocation.java:144)
> 	at com.android.sdklib.repository.AndroidSdkHandler.lambda$getInstance$3(AndroidSdkHandler.java:229)
> 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
> 	at com.android.sdklib.repository.AndroidSdkHandler.getInstance(AndroidSdkHandler.java:224)
> 	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
> 	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
> 
> ERROR: Install failed.
> 
> Please read output for clues, or open an issue on GitHub (https://github.com/mortend/android-build-tools/issues).
> 
> Please note that JDK8 (not 9+) is required to install Android SDK. Get OpenJDK8 from https://adoptopenjdk.net/ and try again.
> + android-build-tools@1.3.0
> updated 1 package in 8.646s

2. Buildjob `xhdt0dtx2o4jb18o`:

> paulofrancisco$ sudo npm install -g -f https://ci.appveyor.com/api/buildjobs/xhdt0dtx2o4jb18o/artifacts/android-build-tools-1.3.0.tgz
> npm WARN using --force I sure hope you know what you are doing.
> 
> '> android-build-tools@1.3.0 install /usr/local/lib/node_modules/android-build-tools
> '> xbash install.bash
> 
> Accepting licenses
> install.bash: line 169: sdkmanager.log: Permission denied
> cat: sdkmanager.log: No such file or directory
> 
> ERROR: Install failed.
> 
> Please read output for clues, or open an issue on GitHub (https://github.com/mortend/android-build-tools/issues).
> 
> Please note that JDK8 (not 9+) is required to install Android SDK. Get OpenJDK8 from https://adoptopenjdk.net/ and try again.
> + android-build-tools@1.3.0
> updated 1 package in 4.002s

3. Buildjob `xhdt0dtx2o4jb18o` without `sudo`:

> paulofrancisco$ npm install -g -f https://ci.appveyor.com/api/buildjobs/xhdt0dtx2o4jb18o/artifacts/android-build-tools-1.3.0.tgz
> npm WARN using --force I sure hope you know what you are doing.
> npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/android-build-tools
> npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
> npm ERR! code EACCES
> npm ERR! syscall mkdir
> npm ERR! path /usr/local/lib/node_modules/.staging
> npm ERR! errno -13
> npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/.staging'
> npm ERR!  [OperationalError: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/.staging'] {
> npm ERR!   cause: [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/.staging'] {
> npm ERR!     errno: -13,
> npm ERR!     code: 'EACCES',
> npm ERR!     syscall: 'mkdir',
> npm ERR!     path: '/usr/local/lib/node_modules/.staging'
> npm ERR!   },
> npm ERR!   stack: "Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/.staging'",
> npm ERR!   errno: -13,
> npm ERR!   code: 'EACCES',
> npm ERR!   syscall: 'mkdir',
> npm ERR!   path: '/usr/local/lib/node_modules/.staging'
> npm ERR! }
> npm ERR! 
> npm ERR! The operation was rejected by your operating system.
> npm ERR! It is likely you do not have the permissions to access this file as the current user
> npm ERR! 
> npm ERR! If you believe this might be a permissions issue, please double-check the
> npm ERR! permissions of the file and its containing directories, or try running
> npm ERR! the command again as root/Administrator.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/paulofrancisco/.npm/_logs/2020-04-24T23_25_55_477Z-debug.log


I'm thinking about formatting my mac and starting from scratch. It all happened after changing Android Build to 64Bits... What do you think?

**Comment by mortend** [comment]
This command should make your `node_modules` writable by your user account.

    sudo chown -R "$(whoami)" "/usr/local/lib/node_modules"

Then you can reinstall the package with right permission.

Additional info: http://npm.github.io/installation-setup-docs/installing/a-note-on-permissions.html

**Comment by Paulofsr** [comment]
@mortend, you are so awesome!!!!!

This command  really fix my problem!!

` sudo chown -R "$(whoami)" "/usr/local/lib/node_modules"`



- Remembering that the `HOME` variable defined was necessary:

`export HOME=/Users/paulofrancisco/`


- And I needed to make this directory writable by my user account:

`sudo chown -R "$(whoami)" "/Users/paulofrancisco/.android/" `


- And finally, I installed `android-build-tools` with the following command:

` 
npm install -g -f https://ci.appveyor.com/api/buildjobs/xhdt0dtx2o4jb18o/artifacts/android-build-tools-1.3.0.tgz
`


 
Follow the success log!!

> paulofrancisco$ npm install -g -f https://ci.appveyor.com/api/buildjobs/xhdt0dtx2o4jb18o/artifacts/android-build-tools-1.3.0.tgz
> npm WARN using --force I sure hope you know what you are doing.
> 
> '> android-build-tools@1.3.0 install /usr/local/lib/node_modules/android-build-tools
> '> xbash install.bash
> 
> Accepting licenses
> Installing cmake;3.10.2.4988404
> Installing ndk;21.0.6113669
> 
>  ~/.unoconfig 
> Android.SDK.Directory: /Users/paulofrancisco/Library/Android/sdk
> Android.NDK.Directory: /Users/paulofrancisco/Library/Android/sdk/ndk/21.0.6113669
> 
> 
> + android-build-tools@1.3.0
> updated 1 package in 37.576s


My build of the app returned to run!!

Thank you very very much!!!!!!! :)
You are awesome!
